# Generated by Django 4.2.8 on 2025-07-16 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'API Call Log',
                'verbose_name_plural': 'API Call Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('moex_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fair_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('own_capital', models.BigIntegerField(blank=True, null=True)),
                ('price_score', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Price Snapshot',
                'verbose_name_plural': 'Price Snapshots',
                'ordering': ['-timestamp'],
            },
        ),
    ]
