# Generated by Django 4.2.8 on 2025-07-19 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_optimize_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apicalllog',
            new_name='price_apica_timesta_cc580b_idx',
            old_name='price_apica_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='apicalllog',
            new_name='price_apica_api_nam_8e4d3e_idx',
            old_name='price_apica_api_nam_idx',
        ),
        migrations.AlterField(
            model_name='apicalllog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
